### ISSUE TITLE
Message Classification - Delete a message

### ISSUE THREAD

**Issue by amcghie** [dwpdigitaltech/queue-triage#20]
Delete a message based upon:
- Value of a property
- Content of a message

Given a message exists on the DLQ with (a property|content) equal to "X"
When the message is dequeued
And a "delete" classifier has been configured with (property|content) equal to "X"
Then the message is marked as deleted

Given a message exists on the DLQ with (a property|content) equal to "X"
When the message is dequeued
And a "delete" classifier has been configured with (property|content) equal to "Y"
Then the message is not deleted.

**Comment by dwp-joaomelo** [comment]
@amcghie I assume by "marked as deleted" we are talking about logical delete, right?

**Comment by amcghie** [comment]
That's what I was thinking and then have a job that physically deletes after n number of days.
