### ISSUE TITLE
Search for Failed Messages by Broker and/or Queue Name

### ISSUE THREAD

**Issue by amcghie** [dwpdigitaltech/queue-triage#28]
When a search is requested with no broker and no queue
Then a BAD_REQUEST response is returned

When a search is requested with no broker and queue "x"
Then a BAD_REQUEST response is returned

Given a failed message with Id "1" was sent to queue "x" on broker "a"
When a search is requested for broker "b"
Then 0 messages are returned

Given a failed message with Id "1" was sent to queue "x" on broker "a"
When a search is requested for broker "a"
Then 1 message is returned with Id "1"

Given a failed message with Id "1" was sent to queue "x" on broker "a"
When a search is requested for broker "a" and queue "y"
Then 0 messages are returned

Given a failed message with Id "1" was sent to queue "x" on broker "a"
When a search is requested for broker "a" and queue "x"
Then 1 message is returned with Id "1"

**Comment by dwp-joaomelo** [comment]
@amcghie this is already done as part of PR 31 right?
