### ISSUE TITLE
Security: Login & Logout

### ISSUE THREAD

**Issue by dwp-joaomelo** [dwpdigitaltech/queue-triage#36]
Scenario: Guest User

Given: I am a guest
When: I access any page (other than login) in queue-triage platform
Then: I am redirected to login page

Scenario: Logging in

Given: I am a guest
And: I am at the login page
When: I enter correct credentials (username & password)
Then: I am redirected to the dashboard

Scenario: Logging out

Given: I am a logged in user
When: I click in the logout link in the menu
Then: I am redirected to the login page
And: I cannot access any page (other than login)

For the login feature we need integration with LDAP

**Comment by amcghie** [comment]
I thought it would be sensible to start on this issue now, rather than trying to retro fit it later

**Comment by amcghie** [comment]
The following endpoints will be left unsecured:

- /login
- /static/*

**Comment by amcghie** [comment]
PR #44 created.
