### ISSUE TITLE
Mongo: Improve mongodb connection options

### ISSUE THREAD

**Issue by amcghie** [dwpdigitaltech/queue-triage#60]
Improve mongodb connection options to allow (optionally):
- Connecting to a replica set
- Authentication 
- Connecting using TLS/SSL

For bonus points it would be good to allow users to specify the above options either via the Connection String (e.g. `mongodb://user1:pwd1@host1/?authSource=db1&ssl=true`) or via individual options

**Comment by amcghie** [comment]
Whilst testing this issue I've identified an issue where the `PropertySourceLoader` is not correctly instantiating the `MongoDaoProperties` object and therefore the default values are used (`localhost:27017`).  This is obviously a blocker for anyone who wants to run this anywhere other than dev/test

**Comment by amcghie** [comment]
I don't think there's anything left to do on this story.  @dwp-joaomelo do you agree?

**Comment by dwp-joaomelo** [comment]
👍 perfeito!
