### ISSUE TITLE
Feature request: Search messages by content

### ISSUE THREAD

**Issue by eric-vlaanderen** [dwpdigitaltech/queue-triage#86]
Would be good to be able to search messages by content to determine if an issue is related to a failed jms message

**Comment by amcghie** [comment]
Started

**Comment by amcghie** [comment]
@eric-vlaanderen do you want to have a look at this pull request?

**Comment by amcghie** [comment]
Remaining work is to plumb the search capability into the front end

**Comment by amcghie** [comment]
Resolved by #94
